# Change these first
owner: krown-one # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Web
    url: https://www.krown.one/
  - name: Dev Web
    url: https://dev.krown.one/
  - name: Lustrall
    url: https://lustrall.krown.one/status
  - name: Assets Impulso
    url: https://branded.krown.one/impulso/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.krown.one
  # baseUrl: /your-repo-name
  logoUrl: https://krown.one/assets/img/logo.svg
  favicon: https://www.krown.one/assets/favicon/favicon-16x16.png
  theme: night
  name: Status Krown
  introTitle: "Status"
  introMessage: home
  navbar:
    - title: Status
      href: /
    - title: Krown
      href: https://www.krown.one/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
